[package]
name = "example_support"
version = "0.0.0-dev"
edition = "2021"
publish = false

[dependencies]
raos = { path = "../raos", version = "=0.0.0-dev" }
rand = "0.8"
tokio = { version = "1", features = ["sync"] }
serde_urlencoded = "0.7"
