name: Merge checks

on: [push]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - &checkout
        name: Checkout git repository
        uses: actions/checkout@v2
      - name: Run clippy
        run: cargo clippy --all -- -D warnings
  formatting:
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - name: Test code formatting
        run: cargo fmt --all -- --check
  tests:
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - name: Run unit tests
        run: cargo test --all --all-features --verbose
