name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Basic tests to ensure code quality before release
      - name: Checkout git repository
        uses: actions/checkout@v2
      - name: Run unit tests
        run: cargo test --all --verbose
      - name: Test code formattinggit
        run: cargo fmt --all -- --check
      - name: Test code correctness
        run: cargo clippy --all -- -D warnings

      # Prepare crate
      - name: Set crate version
        run: find . -name 'Cargo.toml' -exec sed -i "s/0.0.0-dev/$(git describe --tags)/g" {} +
      - name: Publish raos main crate
        run: (cd raos && cargo login ${{ secrets.CRATES_IO_TOKEN }} && cargo publish --allow-dirty) # Dirty because we modified Cargo.toml
      - name: Publish raos_actix crate
        run: (cd raos_actix && cargo login ${{ secrets.CRATES_IO_TOKEN }} && cargo publish --allow-dirty) # Dirty because we modified Cargo.toml
