name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Basic tests to ensure code quality before release
      - name: Checkout git repository
        uses: actions/checkout@v2
      - name: Run unit tests
        run: cargo test --all --all-features
      - name: Test code formatting
        run: cargo fmt --all -- --check
      - name: Test code correctness
        run: cargo clippy --all -- -D warnings

      # Prepare crate
      - name: Set crate version
        run: find . -name 'Cargo.toml' -exec sed -i "s/0.0.0-dev/$(git describe --tags)/g" {} +
      - name: Publish raos main crate
        working-directory: raos
        run: cargo publish --allow-dirty
      - name: Publish raos_actix crate
        working-directory: raos_actix
        run: cargo publish --allow-dirty
