name: Unit tests

on : [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
      - name: Run unit tests
        run: cargo test --all --verbose